# Base configs
baseurl: "https://mouweng.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by mouweng"
subtitle: "See the world through my eyes!"
author: "Mouweng"
header:
 title: "Photography"
 subtitle: "by mouweng"
footer:
 name: "Hi thereğŸ‘‹ğŸ», This is mouweng"
 bio: "A master studying in ZJU ğŸ™‹ğŸ»â€â™‚ï¸ I am also a landscape photographerğŸ“·"
web_design: "AJ"
social_urls:
  twitter: ""
  instagram: ""
  github: "https://www.github.com/mouweng"
