# Base configs
baseurl: "https://mouweng.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by mouweng"
subtitle: "See the world through my eyes!"
author: "Mouweng"
header:
 title: "Photography"
 subtitle: "by mouweng"
footer:
 name: "Hi thereğŸ‘‹ğŸ», This is mouweng"
 bio: "a master studying in ZJU ğŸ™‹ğŸ»â€â™‚ï¸"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/mouweng"
